RemSell/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls'))
 ] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('chats', views.chat, name='chat'),
    path('log', views.log, name='log'),
    path('add_product', views.add_product, name='add_product'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('send_message/', views.send_message, name='send_message'),
    path('get_chat_messages/', views.get_chat_messages, name='get_chat_messages'),
    path('chats/<int:chat_id>/', views.view_chat, name='view_chat'),
    path('profile/<str:username>/', views.profile_user, name='profile_user'),
    path('profile_other/<str:username>/', views.view_other_profile, name='view_other_profile'),
    path('account/settings_user/', views.settings_user, name='settings_user'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('update-username/', views.update_username, name='update_username'),
    path('update-password/', views.update_password, name='update_password'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_security/', views.update_security, name='update_security'),
    path('product-not-available/', views.product_not_available, name='product_not_available'),
    path('logout/', views.my_logout_view, name='logout'),
    path('product/<int:product_id>/order_checkout/', views.order_checkout, name='order_checkout'),
    path('autocomplete-address/', views.autocomplete_address, name='autocomplete_address'),
    path('product/<int:product_id>/order_checkout/order_confirmation/<int:reserved_order_id>/', views.order_confirmation, name='order_confirmation'),
    path('finance/', views.finance, name='finance'),
    path('order/<int:order_id>/pay/', views.pay_order, name='pay_order'),
    path('sales_history/', views.sales_history, name='sales_history'),
    path('ship_order/<int:order_id>/', views.ship_order, name='ship_order'),
    path('product_detail_with_chat/<int:product_id>/<int:order_id>/', views.product_detail_with_chat, name='product_detail_with_chat'),
    path('leave_review/', views.leave_review, name='leave_review'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('update-user-status/', views.update_user_status, name='update_user_status'),
    path('search/', views.search_products, name='search_products'),
    path('block_user/', views.block_user, name='block_user'),
    path('report_user/', views.report_user, name='report_user'),
    path('unblock_user/', views.unblock_user, name='unblock_user'),
    path('order/<int:order_id>/confirm/', views.confirm_payment, name='confirm_payment'),
    path('update_avatar/', views.update_avatar, name='update_avatar')
]

main/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models import Count, Q, Avg
from decimal import Decimal
from django.urls import reverse
from django.utils import timezone


# Часть продукта
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='products/', default='products/default_product_image.jpg')
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    categories = models.ManyToManyField(Category, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.00)
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    def __str__(self):
        return self.name

@receiver(pre_save, sender=Product)
def check_product_availability(sender, instance, **kwargs):
    if instance.quantity == 0:
        instance.available = False
    else:
        instance.available = True

@receiver(pre_save, sender=Product)
def set_seller_default(sender, instance, **kwargs):
    if not instance.seller:
        instance.seller = instance.request.user


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ratings')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='ratings', null=True, blank=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller_ratings', default=None)
    value = models.IntegerField(choices=[(i, i) for i in range(1, 6)])  # Оценка от 1 до 5
    review = models.TextField(blank=True, null=True)  # Письменный отзыв
    image = models.ImageField(upload_to='reviews/', blank=True, null=True)  # Изображение отзыва

    def __str__(self):
        product_name = self.product.name if self.product else "Unknown"
        return f"{self.user.username} - Оценка: {self.value} - Продавец: {self.seller.username} - Товар: {product_name}"

@receiver(post_save, sender=Rating)
def update_user_quality_rating(sender, instance, created, **kwargs):
    if created:
        user = instance.user
        user_quality_rating = calculate_user_quality_rating(user)
        user.userprofile.quality_rating = user_quality_rating
        user.userprofile.save()

        product_avg_rating = Rating.objects.filter(product=instance.product).aggregate(Avg('value'))['value__avg']
        instance.product.rating = product_avg_rating
        instance.product.save()
def calculate_user_quality_rating(user):
    # Получаем все товары, продаваемые пользователем
    user_products = Product.objects.filter(seller=user)

    # Вычисляем средние оценки для всех товаров пользователя
    product_ratings = [product.ratings.aggregate(Avg('value'))['value__avg'] for product in user_products]

    # Исключаем None значения (если товар еще не был оценен)
    product_ratings = [rating for rating in product_ratings if rating is not None]

    # Вычисляем общую среднюю оценку качества пользователя
    if product_ratings:
        user_quality_rating = sum(product_ratings) / len(product_ratings)
        user_quality_rating = round(user_quality_rating, 2)  # Округляем до двух знаков после запятой
    else:
        user_quality_rating = Decimal('0.00')  # Если у пользователя нет оценок, устанавливаем нулевую оценку

    return user_quality_rating


# Часть пользователя
class UserProfile(models.Model):
    STATUS_CHOICES = (
        ('online', 'Online'),
        ('offline', 'Offline'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.jpg')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='online')
    bio = models.TextField(blank=True, null=True)
    quality_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    patronymic = models.CharField(max_length=50, blank=True, null=True)
    last_activity = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=Rating)
def update_user_quality_rating(sender, instance, created, **kwargs):
    if created:
        user = instance.user
        user_ratings = Rating.objects.filter(user=user)
        product_ratings = Rating.objects.filter(product=instance.product)

        # Обновляем рейтинг качества пользователя
        user_quality_rating = calculate_user_quality_rating(user)
        user.userprofile.quality_rating = user_quality_rating
        user.userprofile.save()

        # Обновляем средний рейтинг товара
        product_avg_rating = product_ratings.aggregate(Avg('value'))['value__avg']
        instance.product.rating = product_avg_rating
        instance.product.save()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

# @receiver(post_save, sender=UserProfile)
# def update_user_status(sender, instance, created, **kwargs):
#     if not created and not hasattr(instance, '_status_update_in_progress'):
#         instance._status_update_in_progress = True  # Устанавливаем флаг, чтобы избежать повторного выполнения
#         # Проверяем, была ли активность пользователя за последние 15 минут
#         threshold = timezone.now() - timezone.timedelta(minutes=1)
#         print('a')
#         print(threshold)
#         print(instance.last_activity)
#         if instance.last_activity > threshold:
#             # Если пользователь был неактивен, меняем его статус на "offline"
#             instance.status = 'online'
#         else:
#             # Иначе, пользователь активен, меняем его статус на "online"
#             instance.status = 'offline'
#         # Сохраняем изменения статуса пользователя
#         instance.save()
#         del instance._status_update_in_progress

class UserFinance(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.user.username + "'s finance"



# Часть чата
class Chat(models.Model):
    participants = models.ManyToManyField(User, related_name='chats')
    name = models.CharField(max_length=255, blank=True)  # Поле для названия чата

    def update_name(self):
        self.name = ', '.join(str(participant) for participant in self.participants.all())
        self.save()

    def add_participant(self, participant):
        self.participants.add(participant)
        self.update_name()

    def remove_participant(self, participant):
        self.participants.remove(participant)
        self.update_name()

    def __str__(self):
        if self.name:
            return self.name
        else:
            return ', '.join([str(participant) for participant in self.participants.all()])

    def last_message(self):
        return self.messages.order_by('-timestamp').first()


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

class BlockedUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    blocked_by = models.ForeignKey(User, related_name='blocked_by', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"User: {self.blocked_by} Blocked: {self.user}"

class UserComplaint(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    complainant = models.ForeignKey(User, related_name='complainant', on_delete=models.CASCADE)
    reason = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Chat: {self.chat}, User: {self.user} {self.reason}"


# Способ оплаты
class PaymentMethod(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class DeliveryMethod(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

# Заказ
class Transaction(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchased_transactions')
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sold_transactions')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    is_cancelled = models.BooleanField(default=False)

    def __str__(self):
        return f"Transaction #{self.id}"

    def cancel(self):
        # Если транзакция была отменена, ничего не делаем

main/forms.py
from django import forms
from .models import Product, Rating, UserProfile, PaymentMethod, DeliveryMethod, Category
from django.contrib.auth.models import User

class ProductForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,  # Виджет для отображения чекбоксов
        required=False
    )

    class Meta:
        model = Product
        fields = ['name', 'description', 'quantity', 'image', 'categories', 'price']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ProductForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)
        instance.seller = self.user
        if commit:
            instance.save()
        return instance


class NotificationSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

class SecuritySettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['password']

class UpdateEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            # Дополнительная проверка, если это необходимо
            return email
        else:
            raise forms.ValidationError("Введите корректный email адрес")

class UpdateUsernameForm(forms.Form):
    new_username = forms.CharField(max_length=150)

    def clean_new_username(self):
        new_username = self.cleaned_data.get('new_username')
        if not new_username:
            raise ValidationError("Please enter a new username.")
        return new_username

class AvatarForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['avatar']
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
        }

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['product', 'value', 'review', 'image']


class BioForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio']


class CheckoutForm(forms.Form):
    first_name = forms.CharField(label='Имя', max_length=50)
    last_name = forms.CharField(label='Фамилия', max_length=50)
    patronymic = forms.CharField(label='Отчество', max_length=50)
    email = forms.EmailField(label='Email')
    phone_number = forms.CharField(label='Номер телефона', max_length=15)
    # address = forms.CharField(label='Адрес доставки', widget=forms.Textarea)
    payment_method = forms.ModelChoiceField(label='Способ оплаты', queryset=PaymentMethod.objects.all())
    delivery_method = forms.ModelChoiceField(label='Способ доставки', queryset=DeliveryMethod.objects.all())
    quantity = forms.IntegerField(label='Количество', min_value=1)

main/templates/main/add_product.html
{% extends 'main/log_layout.html' %}
{% load static %}

{% block meta-title %}RemSell{% endblock %}
{% block meta-styles %}
	<link rel="stylesheet" href="{% static 'main/css/add_pr.css' %}">
    <script src="{% static 'main/js/add_product.js' %}"></script>
{% endblock %}
{% block meta-body %}
    <div class="add-product-container">
        <h1 class="add-product-title">Добавить товар</h1>
        <form method="post" enctype="multipart/form-data" class="add-product-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Название товара:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_description">Описание товара:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="id_quantity">Количество:</label>
                {{ form.quantity }}
            </div>
            <div class="form-group">
                <label for="id_image">Изображение товара:</label>
                {{ form.image }}
            </div>
            <div class="form-group">
                <label for="id_category">Категории:</label>
                {{ form.categories }}
            </div>
            <div class="form-group">
                <label for="id_price">Цена:</label>
                {{ form.price }}
            </div>
            <button type="submit" class="add-product-btn">Добавить</button>
        </form>
    </div>
{% endblock %}

main/templates/main/category_products.html
{% extends 'main/log_layout.html' %}
{% load static %}

{% block meta-title %}RemSell{% endblock %}
{% block meta-styles %}
    <link rel="stylesheet" href="{% static 'main/css/test1.css' %}">
    <script src="{% static 'main/js/rating_of_product.js' %}"></script>
{% endblock %}
{% block meta-body %}

    <main class="product-catalog">
		<div class="add-button-container">
            <div class="add-product-button">
                <button class="add-product-btn" onclick="redirectToAddProduct()">Добавить товар</button>
            </div>
            <div class="border-text-container">
                Указывайте действительные товары, находящиеся у вас в наличии
            </div>
        </div>
        <div>
            <h1 class="category-title">{{ category.name }}</h1>
        </div>
        <div class="product-line-all">
<!--            <div id="search-results"></div>-->
            {% for product in products %}
                {% if product.available %}
                    <div class="product">
                        <a href="{% url 'product_detail' product.id %}">
                            <div class="product-card">
                                <div class="product-image">
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                </div>
                                <div class="product-details">
                                    <span class="product-title dt1">{{ product.name }}</span>
                                    <span class="product-description dt">{{ product.description|linebreaksbr }}</span>
                                    <span class="product-quantity dt">Количество: {{ product.quantity }} шт.</span>
                                    <div class="product-rating">
                                        {% for i in stars_range %}
                                            {% if i <= product.avg_rating %}
                                                <svg class="reviews-star" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                                </svg>
                                            {% else %}
                                                <svg class="rating-star" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                                </svg>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

	</main>

{% endblock %}

main/templates/main/chat.html
{% extends 'main/log_layout.html' %}
{% load static %}

{% block meta-title %}Чаты{% endblock %}

{% block meta-styles %}
    <link rel="stylesheet" href="{% static 'main/css/chat.css' %}">
	<script src="{% static 'main/js/test2_chat_update.js' %}"></script>
{% endblock %}

{% block meta-body %}
    <div class="chat-container" id="chat-container">
		<div class="user-box">
			<div class="user-header-bar">
				<h2>Сообщения</h2>
			</div>
			<div class="user-list">
				<ul>
					{% for chat in user_chats %}
						{% if chat.participants.count == 2 %}
							<li data-chat-id="{{ chat.id }}">
								<div class="user-avatar">
                                    <img src="{{ chat.interlocutor_avatar }}" alt="{{ chat.name }}">
                                </div>
								<a class="chatters-name-list" href="{% url 'view_chat' chat.id %}">{{ chat.name }}</a>
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="chat-box">
			<div>

			</div>
		</div>

		<div class="chat-input">
				<form id="message-form" data-send-message-url="{% url 'send_message' %}">
					{% csrf_token %}
					<input type="hidden" id="chat-id" name="chat_id" value="{{ chat.id }}">
				</form>
		</div>

		<div class="group-chat-box">
			<div class="user-header-bar">

			</div>
			<div class="reg-interlocutor-info">

			</div>
		</div>
	</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.user-list li').click(function() {
            	var chatId = $(this).data('chat-id');
                var url = $(this).find('a').attr('href') + '?chat_id=' + chatId;
                if (url) {
                    window.location.href = url;
                }
            });
        });
    </script>
{% endblock %}

main/templates/main/finance.html
{% extends 'main/log_layout.html' %}
{% load static %}

{% block meta-title %}RemSell{% endblock %}
{% block meta-styles %}
    <link rel="stylesheet" href="{% static 'main/css/finance_page.css' %}">
{% endblock %}
{% block meta-body %}
	<main>
        <h1>Мои покупки</h1>
        <div class="finance-details">
            <h2>Мои покупки</h2>
            <div class="tc-header text-bold">
            <div class="hidden-xs mw150">Дата</div>
            <div class="hidden-xs">Заказ</div>
            <div>Описание</div>
            <div class="hidden-xs mw150">Продавец</div>
            <div class="hidden-xs">Статус</div>
            <div class="tc-price col-lg-2">Сумма</div>
            </div>
            <ul>
                {% for order in orders %}
                <a href="{% url 'product_detail_with_chat' product_id=order.product.id order_id=order.id %}">
                    <li>
                        <div class="hidden-xs mw150"><p>{{ order.created_at }}</p></div>
                        <div class="hidden-xs"><p>#{{ order.serial_number }}</p></div>
                        <div><p>{{ order.product.name }}</p></div>
                        <div class="hidden-xs mw150"><p>{{ order.product.seller }}</p></div>
                        <div class="hidden-xs">
                            <p>{% if order.delivered %} Доставлен {% else %} Не доставлен {% endif %}</p>
<!--                            <p>{% if order.paid %} Оплачен {% else %} Не оплачен {% endif %}</p>-->
                            {% if not order.paid %}
                                <form id="pay-form-{{ order.id }}" method="post" action="{% url 'pay_order' order.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="pay-button">Оплатить</button>
                                </form>
                            {% endif %}
                        </div>
                        <div class="tc-price col-lg-2"><p>{{ order.total_amount }}</p></div>
                    </li>
                </a>
                {% endfor %}
            </ul>
            <ul>
                {% for sale in sales %}
                <a href="{% url 'product_detail_with_chat' product_id=sale.product.id order_id=sale.id %}">
                    <li>
                        <div class="hidden-xs mw150"><p>{{ sale.created_at }}</p></div>
                        <div class="hidden-xs"><p>#{{ sale.serial_number }}</p></div>
                        <div><p>{{ sale.product.name }}</p></div>
                        <div class="hidden-xs mw150"><p>{{ sale.product.seller }}</p></div>  <!-- Use sale.product.seller -->
                        {% if sale.transaction.is_cancelled %}
                            <div class="hidden-xs">
                                <p class="imitate-button-backend">Заказ отменен</p>
                            </div>
                        {% else %}
                            <div class="hidden-xs">
                                <p>{% if sale.delivered %} Доставлен {% else %} Не доставлен {% endif %}</p>
                                <p class="imitate-button-paid {% if sale.paid %}paid{% else %}not-paid{% endif %}">{% if sale.paid %} Оплачен {% else %} Не оплачен {% endif %}</p>
                            </div>
                        {% endif %}
                        <div class="tc-price col-lg-2">
                            {% if not sale.paid %}
                                <p class="not-paid">{{ sale.total_amount }}</p>
                            {% else %}
                                {% if not sale.transaction.is_cancelled %}
                                    <p class="paid-negative">-{{ sale.total_amount }}</p>
                                {% else %}
                                    <p class="paid-positive">+{{ sale.total_amount }}</p>
                                {% endif %}
                            {% endif %}
                        </div>
                    </li>
                </a>
                {% endfor %}
            </ul>
        </div>
    </main>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            document.querySelectorAll('.pay-button').forEach(button => {
                button.addEventListener('click', function(event) {
                    event.preventDefault();
                    const form = this.closest('form');
                    fetch(form.action, {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}',
                        },
                        body: new FormData(form),
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.message === 'Payment successful') {
                            // Optionally update UI to reflect successful payment
                            location.reload(); // Reload the page to reflect changes
                        } else {
                            // Optionally handle error messages
                            console.error('Payment error:', data.message);
                        }
                    })
                    .catch(error => {
                        console.error('Payment error:', error);
                    });
                });
            });
        });
    </script>
{% endblock %}

main/templates/main/product_not_available.html
{% extends 'main/log_layout.html' %}
{% load static %}

{% block meta-title %}RemSell{% endblock %}
{% block meta-styles %}
    <link rel="stylesheet" href="{% static 'main/css/product_not_found_page.css' %}">
{% endblock %}
{% block meta-body %}
	<main class="--">
        <div class="content">
            <h1>Продукт недоступен</h1>
            <p>Товар, который вы ищете, больше не доступен.</p>
        </div>
    </main>
{% endblock %}